### ISSUE TITLE
Lack of call to super() breaks bundling boom for the browser

### ISSUE THREAD

**Issue by dejitaiza** [hapijs/boom#204] opened 2018-08-04 12:29 UTC
Hello amazing Hapi community,

I am trying to bundle an npm module that depends on boom, and I get this error (that seems to be related to babel parsing):

```
node_modules/boom/lib/index.js: missing super() call in constructor
  78 |     }
  79 |
> 80 |     constructor(message, options = {}) {
     |     ^
  81 |
  82 |         if (message instanceof Error) {
  83 |             return internals.Boom.boomify(Hoek.clone(message), options);
```

Adding a call to `super()` in the constructor seems to resolve it.

Now I am not sure if this should be reported to Boom or to Babel, so please excuse me if this issue is irrelevant, however by looking at this constructor's implementation, it seems adding `super()` will not break anything, as the constructor creates a `new Error(...)` later and returns it.

Would you be open to a PR that adds this line?

**Comment by kanongil** [comment] 2018-08-04 14:08
Duplicate of 
https://github.com/hapijs/boom/pull/185.

**Closed by kanongil** 2018-08-04 14:08 UTC
Labels: non-issue
