### ISSUE TITLE
Expose error name/error/statusCode in top-level

### ISSUE THREAD

**Issue by dwelle** [hapijs/boom#145] opened 2017-03-02 09:55 UTC
Currently there's no easy way to determine what type of error we're dealing with if supplied as an argument down the line, e.g. when handling rejected promises I need to do this:

```
.catch( err => {
  if ( err.isBoom && err.output.payload.error=== "Not Found" ) {
    // handle 404
  } else {
    reply( err );
  }
});
```

If I want to sacrifice readability for concision, at best I can access `err.output.statusCode`.

Seems fishy to have to access `output` to determine what type of error we're dealing with. I can't depend on `err.message` which may differ, and don't want/may not be able to be setting custom data all the time.

Shouldn't Boom expose `error` as top-level property, or replace the `name` (Joi does that)?

```
Boom.badRequest().name === "BadRequest";
// or
Boom.badRequest().error === "Bad Request";
// or at least
Boom.badRequest().statusCode === 400;
```

**Comment by hueniverse** [comment] 2017-03-20 20:08
Replacing the name is a breaking change. I do fine with using the status code. Setting a new property should be fine.

**Comment by hueniverse** [comment] 2017-03-21 06:53
Duplicate of #138

**Closed by hueniverse** 2017-03-21 06:53 UTC
Labels: request
